# app/config/routing.yml

#HWIOAuthBundle routes
#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect


#NFQAkademijaRecipesBundle routes
nfq_akademija_recipes:
    resource: "@NFQAkademijaRecipesBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml