<?php

namespace NFQAkademija\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeRepository extends EntityRepository
{
}
