nfq_akademija_recipes_homepage:
    pattern:  /
    defaults: { _controller: NFQAkademijaRecipesBundle:Home:index }

nfq_akademija_profile:
    pattern:  /profile
    defaults: { _controller: NFQAkademijaRecipesBundle:Profile:index }

nfq_akademija_shoppinglist:
    pattern:  /shoppinglist
    defaults: { _controller: NFQAkademijaRecipesBundle:ShoppingList:index }

nfq_akademija_cook:
    pattern:  /cook/{recipe_ID}
    defaults: { _controller: NFQAkademijaRecipesBundle:Cook:index }