nfq_akademija_recipes_homepage:
    pattern:  /
    defaults: { _controller: NFQAkademijaRecipesBundle:Home:index }

nfq_akademija_profile:
    pattern:  /profile
    defaults: { _controller: NFQAkademijaRecipesBundle:Profile:index }

nfq_akademija_shoppinglist:
    pattern:  /shoppinglist
    defaults: { _controller: NFQAkademijaRecipesBundle:ShoppingList:index }

nfq_akademija_cook:
    pattern:  /cook/{recipe_ID}
    defaults: { _controller: NFQAkademijaRecipesBundle:Cook:index }

nfq_akademija_places:
    pattern:  /places
    defaults: { _controller: NFQAkademijaRecipesBundle:Places:index }

nfq_akademija_new:
    pattern:  /new
    defaults: { _controller: NFQAkademijaRecipesBundle:New:index }

nfq_akademija_admin:
    pattern:  /admin_zone
    defaults: { _controller: NFQAkademijaRecipesBundle:AdminLogin:index }

nfq_akademija_admin_type:
    pattern:  /admin_zone/{type}
    defaults: { _controller: NFQAkademijaRecipesBundle:Admin:index }

nfq_akademija_new_recipe:
    pattern:  /ajax/new_recipe
    defaults: { _controller: NFQAkademijaRecipesBundle:Ajax:new_recipe }