nfq_akademija_recipes_homepage:
    pattern:  /
    defaults: { _controller: NFQAkademijaRecipesBundle:Home:index }

nfq_akademija_profile:
    pattern:  /profile
    defaults: { _controller: NFQAkademijaRecipesBundle:Profile:index }

nfq_akademija_shoppinglist:
    pattern:  /shoppinglist
    defaults: { _controller: NFQAkademijaRecipesBundle:ShoppingList:index }

nfq_akademija_cook:
    pattern:  /cook/{recipe_ID}
    defaults: { _controller: NFQAkademijaRecipesBundle:Cook:index }

nfq_akademija_new_recipe:
    pattern: /new
    defaults: { _controller: NFQAkademijaRecipesBundle:Recipe:new }


nfq_akademija_new_product:
    pattern: /newproduct
    defaults: { _controller: NFQAkademijaRecipesBundle:Product:new }

nfq_akademija_new_category:
    pattern: /newcategory
    defaults: { _controller: NFQAkademijaRecipesBundle:Category:new }

nfq_akademija_new_country:
    pattern: /newcountry
    defaults: { _controller: NFQAkademijaRecipesBundle:Country:new }

nfq_akademija_new_property:
    pattern: /newproperty
    defaults: { _controller: NFQAkademijaRecipesBundle:Property:new }

nfq_akademija_places:
    pattern:  /places
    defaults: { _controller: NFQAkademijaRecipesBundle:Places:index }

nfq_akademija_new_type:
    pattern: /newtype
    defaults: { _controller: NFQAkademijaRecipesBundle:Type:new }

nfq_akademija_new_cooking_time:
    pattern: /newcookingtime
    defaults: { _controller: NFQAkademijaRecipesBundle:CookingTime:new }

nfq_akademija_new_celebration:
    pattern: /newcelebration
    defaults: { _controller: NFQAkademijaRecipesBundle:Celebration:new }

nfq_akademija_new_fact:
    pattern: /newfact
    defaults: { _controller: NFQAkademijaRecipesBundle:Fact:new }

nfq_akademija_new_location:
    pattern: /newlocation
    defaults: { _controller: NFQAkademijaRecipesBundle:Location:new }

nfq_akademija_new_method:
    pattern: /newmethod
    defaults: { _controller: NFQAkademijaRecipesBundle:MainCookingMethod:new }

nfq_akademija_new_step:
    pattern: /newstep
    defaults: { _controller: NFQAkademijaRecipesBundle:Step:new }