nfq_akademija_recipes_homepage:
    pattern:  /
    defaults: { _controller: NFQAkademijaRecipesBundle:Home:index }

nfq_akademija_profile:
    pattern:  /profile
    defaults: { _controller: NFQAkademijaRecipesBundle:Profile:index }

nfq_akademija_shoppinglist:
    pattern:  /shoppinglist
    defaults: { _controller: NFQAkademijaRecipesBundle:ShoppingList:index }

nfq_akademija_random:
    pattern:  /random
    defaults: { _controller: NFQAkademijaRecipesBundle:Random:index }

nfq_akademija_new_recipe:
    pattern:  /new
    defaults: { _controller: NFQAkademijaRecipesBundle:Recipe:new }



