nfq_akademija_recipes_homepage:
    pattern:  /
    defaults: { _controller: NFQAkademijaRecipesBundle:Home:index }

nfq_akademija_profile:
    pattern:  /profile
    defaults: { _controller: NFQAkademijaRecipesBundle:Profile:index }

nfq_akademija_shoppinglist:
    pattern:  /shoppinglist
    defaults: { _controller: NFQAkademijaRecipesBundle:ShoppingList:index }

nfq_akademija_cook:
    pattern:  /cook/{id}
    defaults: { _controller: NFQAkademijaRecipesBundle:Cook:index }

nfq_akademija_places:
    pattern:  /places
    defaults: { _controller: NFQAkademijaRecipesBundle:Places:index }

nfq_akademija_search:
    pattern:  /ajax/search
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxSearch:search}

nfq_akademija_search_shoppinglist:
    pattern:  /ajax/search_shoppinglist
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxSearch:search_shoppinglist}

nfq_akademija_search_places:
    pattern:  /ajax/search_places
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxSearch:search_places}

nfq_akademija_filters_show:
    pattern:  /ajax/filters_show
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxFilters:filters_show}

nfq_akademija_filter_indicator_change:
    pattern:  /ajax/filter_indicator_change
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxFilters:filter_indicator_change}

nfq_akademija_add_to_shoppinglist:
    pattern:  /ajax/add_to_shoppinglist
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxShoppinglist:add_to_shoppinglist}

nfq_akademija_remove_from_shoppinglist:
    pattern:  /ajax/remove_from_shoppinglist
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxShoppinglist:remove_from_shoppinglist}

nfq_akademija_load_profile_recipes:
    pattern:  /ajax/load_profile_recipes
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxLoad:load_profile_recipes }

nfq_akademija_load_recipes:
    pattern:  /ajax/load_recipes
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxLoad:load_recipes }

nfq_akademija_load_products:
    pattern:  /ajax/load_products
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxLoad:load_products}

nfq_akademija_loading_screen:
    pattern:  /ajax/loading_screen
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxLoad:loading_screen}

nfq_akademija_load_recipe_in_sidebar:
    pattern:  /ajax/load_recipe_in_sidebar
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxLoad:load_recipe_in_sidebar}

nfq_akademija_coop_info:
    pattern:  /ajax/coop_info
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxSocial:coop_info}

nfq_akademija_login:
    pattern:  /ajax/login
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxSocial:login}

nfq_akademija_like:
    pattern:  /ajax/like
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxSocial:like}

nfq_akademija_share:
    pattern:  /ajax/share
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxSocial:share}

nfq_akademija_comment:
    pattern:  /ajax/comment
    defaults: { _controller: NFQAkademijaRecipesBundle:AjaxSocial:comment}











nfq_akademija_new:
    pattern:  /new
    defaults: { _controller: NFQAkademijaRecipesBundle:New:index }


nfq_akademija_new_recipe:
    pattern:  /ajax/new_recipe
    defaults: { _controller: NFQAkademijaRecipesBundle:Ajax:new_recipe }



nfq_akademija_admin_login:
    pattern:  /admin_zone
    defaults: { _controller: NFQAkademijaRecipesBundle:Admin:login }

nfq_akademija_admin_type:
    pattern:  /admin_zone/{type}
    defaults: { _controller: NFQAkademijaRecipesBundle:Admin:index }

nfq_akademija_admin_logout:
    pattern:  /ajax/admin_logout
    defaults: { _controller: NFQAkademijaRecipesBundle:Ajax:admin_logout}

nfq_akademija_ajax_admin_login:
    pattern:  /ajax/admin_login
    defaults: { _controller: NFQAkademijaRecipesBundle:Ajax:admin_login}

nfq_akademija_admin_load_data:
    pattern:  /ajax/admin_load_data
    defaults: { _controller: NFQAkademijaRecipesBundle:Ajax:admin_load_data}

nfq_akademija_admin_new_data:
    pattern:  /ajax/admin_new_data
    defaults: { _controller: NFQAkademijaRecipesBundle:Ajax:admin_new_data}

nfq_akademija_admin_save_data:
    pattern:  /ajax/admin_save_data
    defaults: { _controller: NFQAkademijaRecipesBundle:Ajax:admin_save_data}

nfq_akademija_admin_delete_data:
    pattern:  /ajax/admin_delete_data
    defaults: { _controller: NFQAkademijaRecipesBundle:Ajax:admin_delete_data}

nfq_akademija_admin_load_selects:
    pattern:  /ajax/admin_load_selects
    defaults: { _controller: NFQAkademijaRecipesBundle:Ajax:admin_load_selects}