parameters:
#    nfq_akademija_base.example.class: NFQAkademija\BaseBundle\Example

services:
#    nfq_akademija_base.example:
#        class: %nfq_akademija_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
