parameters:
    fouser_provider.class: NFQAkademija\BaseBundle\Security\FOSUBUserProvider
 
services:
    fouser_provider:
        class: "%fouser_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]